server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://jiangzh:jiangzh123@localhost:8761/eureka/

zuul:
  prefix: "/meetingfilm/"  ## 统一前缀
  routes:
    meetingfilm-user:
      path: /userapi/**
      serviceId: user-service
      retryable: true   # 是否允许重试 ， 饿汉模式 是针对多个节点的情况的
    meetingfilm-cinema:
      path: /cinemaapi/**
      serviceId: cinema-service
      retryable: true
    meetingfilm-film:
      path: /filmapi/**
      serviceId: film-service
      retryable: true
    meetingfilm-hall:
      path: /hallapi/**
      serviceId: hall-service
      retryable: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000

logging:
  config: classpath:logback.xml